// ===================== ARCHIMATE EXCHANGE FORMAT IMPORT =====================
// Parses an ArchiMate 3.0 Exchange Format XML document (<model> root in the
// http://www.opengroup.org/xsd/archimate/3.0/ namespace) into DyCAD Part/Connector/
// View/ViewMember records.
//   - <organizations> (the folder tree grouping elements for navigation in tools like
//     Archi) is NOT imported — it's purely presentational, and DyCAD has no folder/
//     tree concept for parts to map it onto.
//   - <views>/<diagrams>/<view> ARE imported — one DyCAD View per ArchiMate view,
//     walking its (possibly nested) <node> elements for placement and its <connection>
//     elements for wiring. Diagram nodes with no elementRef (pure visual grouping boxes
//     or free-floating labels — xsi:type="Label" in practice) are skipped; DyCAD has
//     no equivalent visual-grouping concept for viewMembers.
//   - AndJunction/OrJunction elements are NOT imported as Parts at all — see below.
//
// Junction flattening: a junction (AndJunction/OrJunction) is structurally a routing
// node with N incoming relationships and M outgoing ones. Rather than importing it as a
// Part (DyCAD has no multi-way-routing connector concept), every junction is DISSOLVED
// at both the model level and the view level:
//   - Model level: for each junction, every incoming source is directly connected to
//     every outgoing target (the full cross product), using the relationship type of
//     the outgoing edge closest to each real target. Each such target's `note` gets a
//     line like "incoming uses AND logic" / "incoming uses OR logic" recording what the
//     now-removed junction used to mean. Chained junctions (one junction feeding
//     another) are resolved recursively back to real, non-junction endpoints, and the
//     resulting (source, target, relationship) triples are deduplicated globally so a
//     chain doesn't produce the same direct connector twice.
//   - View level: any diagram node whose elementRef is a junction is skipped (no
//     viewMember created for it); wherever the same view already places both a
//     generated connector's real source part and real target part, a connector
//     viewMember is created for that direct (bypass) connector too, so the diagram
//     visually matches the flattened model instead of showing a dangling gap where the
//     junction used to be.
//
// Re-importing the same file is idempotent by design: unlike Import Data's
// user-choosable newKeys option, this importer always keeps the exchange format's own
// <identifier> values as the Part/Connector/View id (they're globally-stable UUIDs
// prefixed "id-", designed for exactly this kind of stable cross-tool reference) and
// merges by id — re-running the same import updates existing records in place rather
// than duplicating them, the same way Generate Industry's repeat-run behavior works
// (Step 29). Generated junction-bypass connectors use a derived, stable id
// (`junction-bypass-<sourceId>-<targetId>-<relType>`) so re-imports don't duplicate
// those either.

const XSI_NS = 'http://www.w3.org/2001/XMLSchema-instance';
const ARCHIMATE_NS = 'http://www.opengroup.org/xsd/archimate/3.0/';
const JUNCTION_TYPES = { AndJunction: 'AND', OrJunction: 'OR' };

function getXsiType(el) {
  return el.getAttributeNS(XSI_NS, 'type') || el.getAttribute('xsi:type') || '';
}

function getChildText(el, tagName) {
  const child = el.getElementsByTagName(tagName)[0];
  return child ? child.textContent.trim() : '';
}

/** Recursively resolves a (possibly-junction) node id to the set of real, non-junction
 * ids reachable by walking only-through-junctions in the given direction, each tagged
 * with the relationship type of the LAST hop into that real id (the edge closest to the
 * real endpoint — used as the generated bypass connector's relationship type).
 * direction 'backward': walk incoming edges (used to find a junction's real sources).
 * direction 'forward': walk outgoing edges (used to find a junction's real targets). */
function resolveThroughJunctions(startId, junctionIds, incomingByTarget, outgoingBySource, direction, edgeTypeIntoStart, visited) {
  if (visited.has(startId)) return []; // guard against pathological cycles
  visited.add(startId);
  if (!junctionIds.has(startId)) return [{ id: startId, relType: edgeTypeIntoStart }];
  const edges = direction === 'backward' ? (incomingByTarget.get(startId) || []) : (outgoingBySource.get(startId) || []);
  const results = [];
  for (const edge of edges) {
    const nextId = direction === 'backward' ? edge.from : edge.to;
    results.push(...resolveThroughJunctions(nextId, junctionIds, incomingByTarget, outgoingBySource, direction, edge.type, new Set(visited)));
  }
  return results;
}

/** Recursively walks a diagram's own <node> parent/child structure (NOT the flattened
 * getElementsByTagName list used elsewhere — this one needs real ancestry), collecting
 * every (ancestorElementRef, descendantElementRef) pair for elements nested at any
 * depth. Used to detect Composition/Aggregation relationships some ArchiMate authors
 * represent by drawing one shape inside another instead of (or as well as) an explicit
 * connecting line — see the nested-shape detection block below. */
function collectNestedElementPairs(parentEl, ancestors, results) {
  const children = [...parentEl.children].filter((c) => c.localName === 'node');
  for (const child of children) {
    const childElRef = child.getAttribute('elementRef');
    if (childElRef) {
      for (const ancestorElRef of ancestors) results.push({ ancestorElRef, childElRef });
    }
    collectNestedElementPairs(child, childElRef ? [...ancestors, childElRef] : ancestors, results);
  }
}

/**
 * Parses ArchiMate Exchange Format XML text. `knownElementTypes` is a Set of type
 * strings DyCAD already has an element definition for (store.settings.elements) —
 * used only to report which imported types have no matching definition (they still
 * import fine, just render with the generic Unknown-type grey fallback until a
 * definition is added).
 * Returns { modelName, parts, connectors, views, viewMembers, unrecognizedTypes } —
 * plain data, no store mutation here; the caller merges it into store.doc.
 */
function parseArchimateXml(xmlText, knownElementTypes, elementDefs, elementGroupFills) {
  const parser = new DOMParser();
  const doc = parser.parseFromString(xmlText, 'application/xml');
  const parseError = doc.querySelector('parsererror');
  if (parseError) throw new Error(`Not well-formed XML: ${parseError.textContent.slice(0, 200)}`);

  const root = doc.documentElement;
  if (root.localName !== 'model' || root.namespaceURI !== ARCHIMATE_NS) {
    throw new Error('Not an ArchiMate 3.0 Exchange Format file (expected a <model> root in the archimate/3.0 namespace).');
  }

  const modelName = getChildText(root, 'name') || 'Imported ArchiMate Model';
  const typeToFill = new Map(); // Part.type -> its element-group's default fill color, for correctly-colored view placement below
  for (const def of elementDefs || []) {
    const fill = (elementGroupFills || new Map()).get(def.group);
    typeToFill.set(def.type, fill || '#cccccc');
  }

  // ---------- elements -> parts (junctions excluded entirely) ----------
  const parts = [];
  const junctionIds = new Set();
  const junctionTypeById = new Map(); // id -> 'AND' | 'OR'
  const unrecognizedTypes = new Set();
  const elementsWrapper = root.getElementsByTagName('elements')[0];
  const elementEls = elementsWrapper ? elementsWrapper.getElementsByTagName('element') : [];
  for (const el of elementEls) {
    const id = el.getAttribute('identifier');
    const type = getXsiType(el);
    if (!id || !type) continue; // skip malformed entries rather than aborting the whole import
    if (JUNCTION_TYPES[type]) {
      junctionIds.add(id);
      junctionTypeById.set(id, JUNCTION_TYPES[type]);
      continue; // no Part created for junctions
    }
    if (!knownElementTypes.has(type)) unrecognizedTypes.add(type);
    const label = getChildText(el, 'name') || type;
    parts.push({
      id, type, label, rawLabel: label,
      model: modelName, streams: [], note: '', order: 0, other: {},
      xIds: '', description: getChildText(el, 'documentation'),
      script: '', scriptEnabled: false,
    });
  }
  const partIds = new Set(parts.map((p) => p.id));
  const partById = new Map(parts.map((p) => [p.id, p]));

  // ---------- relationships -> connectors, with junction edges set aside ----------
  const connectors = [];
  const incomingByTarget = new Map(); // targetId -> [{from, type}] — "who feeds this junction"
  const outgoingBySource = new Map(); // sourceId -> [{to, type}]
  const relationshipRefToConnectorId = new Map(); // original relationship id -> surviving connector id (view <connection> resolution)
  const relationshipsWrapper = root.getElementsByTagName('relationships')[0];
  const relEls = relationshipsWrapper ? relationshipsWrapper.getElementsByTagName('relationship') : [];
  for (const r of relEls) {
    const id = r.getAttribute('identifier');
    const source = r.getAttribute('source');
    const target = r.getAttribute('target');
    const type = getXsiType(r) || 'Association';
    if (!id || !source || !target) continue;

    if (!incomingByTarget.has(target)) incomingByTarget.set(target, []);
    incomingByTarget.get(target).push({ from: source, type });
    if (!outgoingBySource.has(source)) outgoingBySource.set(source, []);
    outgoingBySource.get(source).push({ to: target, type });

    if (junctionIds.has(source) || junctionIds.has(target)) continue; // absorbed into the bypass cross-product below
    connectors.push({ id, from: source, to: target, model: modelName, streams: [], note: '', connectorType: 'c', relationship: type });
    relationshipRefToConnectorId.set(id, id);
  }

  // ---------- index Composition/Aggregation relationships for nested-shape detection ----------
  // ArchiMate authors sometimes represent a whole-part relationship by drawing the
  // "part" shape nested inside the "whole" shape's boundary rather than an explicit
  // connecting line — a standard convention, not a malformed diagram. Indexed by BOTH
  // possible ancestor/child orientations since nesting doesn't encode a direction the
  // way an explicit connection's source/target attributes do.
  const NESTABLE_TYPES = new Set(['Composition', 'Aggregation']);
  const nestableRelByPairKey = new Map(); // "elA|elB" -> {id, from, to, type} (from/to = the relationship's own source/target)
  for (const r of relEls) {
    const id = r.getAttribute('identifier');
    const source = r.getAttribute('source');
    const target = r.getAttribute('target');
    const type = getXsiType(r);
    if (!id || !source || !target || !NESTABLE_TYPES.has(type)) continue;
    const info = { id, from: source, to: target, type };
    nestableRelByPairKey.set(`${source}|${target}`, info);
    nestableRelByPairKey.set(`${target}|${source}`, info);
  }

  // ---------- flatten every junction into direct bypass connectors + notes ----------
  const notesByTargetId = new Map(); // partId -> Set<string>
  const seenBypassKeys = new Set(); // dedupe across chained junctions resolving to the same triple

  for (const junctionId of junctionIds) {
    const logicWord = junctionTypeById.get(junctionId); // 'AND' | 'OR'
    const sources = resolveThroughJunctions(junctionId, junctionIds, incomingByTarget, outgoingBySource, 'backward', null, new Set());
    const targets = resolveThroughJunctions(junctionId, junctionIds, incomingByTarget, outgoingBySource, 'forward', null, new Set());
    for (const s of sources) {
      if (!partIds.has(s.id)) continue; // dangling/unresolved reference — skip rather than fabricate a connector to nowhere
      for (const t of targets) {
        if (!partIds.has(t.id)) continue;
        const relType = t.relType || 'Association';
        const key = `${s.id}|${t.id}|${relType}`;
        if (!seenBypassKeys.has(key)) {
          seenBypassKeys.add(key);
          const bypassId = `junction-bypass-${s.id}-${t.id}-${relType}`.replace(/\s+/g, '_');
          connectors.push({ id: bypassId, from: s.id, to: t.id, model: modelName, streams: [], note: '', connectorType: 'c', relationship: relType });
        }
        if (!notesByTargetId.has(t.id)) notesByTargetId.set(t.id, new Set());
        notesByTargetId.get(t.id).add(`incoming uses ${logicWord} logic`);
      }
    }
  }
  // apply accumulated notes to their target parts
  for (const p of parts) {
    if (notesByTargetId.has(p.id)) {
      const lines = [...notesByTargetId.get(p.id)];
      p.note = p.note ? `${p.note}\n${lines.join('\n')}` : lines.join('\n');
    }
  }

  // ---------- views ----------
  const views = [];
  const viewMembers = [];
  const viewsWrapper = root.getElementsByTagName('views')[0];
  const diagramsWrapper = viewsWrapper ? viewsWrapper.getElementsByTagName('diagrams')[0] : null;
  const viewEls = diagramsWrapper ? [...diagramsWrapper.children].filter((c) => c.localName === 'view') : [];

  for (const viewEl of viewEls) {
    const viewId = viewEl.getAttribute('identifier');
    if (!viewId) continue;
    const viewName = getChildText(viewEl, 'name') || 'Imported View';
    views.push({
      id: viewId, viewName, viewType: 'ff',
      chkShowConnectorType: true, chkShowStreamType: false, chkShowKeys: false,
      chkShowElementTypes: true, chkShowDescription: true, chkShowOnPageCatalogs: false,
      chkShowSimValues: false, chkShowScriptBadge: false, chkShowAllText: false,
      margin: 50, sections: [], nodeWidth: 130, nodeHeight: 46, remapSortKeys: null, spacingScale: 1,
    });

    // recursively collect every <node> (nested groups included); diagram-node-id ->
    // viewMember id, and separately partId -> viewMember id (for bypass-connector wiring)
    const diagramNodeIdToVmId = new Map();
    const partIdToVmId = new Map();
    const nodeEls = [...viewEl.getElementsByTagName('node')];
    for (const nodeEl of nodeEls) {
      const diagramNodeId = nodeEl.getAttribute('identifier');
      const elementRef = nodeEl.getAttribute('elementRef');
      if (!diagramNodeId || !elementRef) continue; // pure visual/group/label node — no DyCAD equivalent
      if (junctionIds.has(elementRef)) continue; // junction's own diagram placement is dissolved along with the junction
      if (!partIds.has(elementRef)) continue; // dangling reference
      const x = Number(nodeEl.getAttribute('x')) || 0;
      const y = Number(nodeEl.getAttribute('y')) || 0;
      const vmId = `vm-${diagramNodeId}`;
      diagramNodeIdToVmId.set(diagramNodeId, vmId);
      partIdToVmId.set(elementRef, vmId);
      const part = partById.get(elementRef);
      const fillColor = (part && typeToFill.get(part.type)) || '#cccccc';
      viewMembers.push({
        id: vmId, view: viewId, objectType: 'part', objectId: elementRef,
        x, y, fillColor, order: 0, note: '', linkedViewName: '', isExternal: false, sectionId: '',
      });
    }

    // <connection> elements -> connector viewMembers, for relationships that survived
    // as normal (non-junction-touching) connectors
    const connEls = [...viewEl.getElementsByTagName('connection')];
    const placedConnectorIds = new Set();
    for (const connEl of connEls) {
      const relRef = connEl.getAttribute('relationshipRef');
      const srcNodeId = connEl.getAttribute('source');
      const tgtNodeId = connEl.getAttribute('target');
      if (!relRef || !srcNodeId || !tgtNodeId) continue;
      const fromVmId = diagramNodeIdToVmId.get(srcNodeId);
      const toVmId = diagramNodeIdToVmId.get(tgtNodeId);
      if (!fromVmId || !toVmId) continue; // one endpoint was a skipped group/junction node

      if (relationshipRefToConnectorId.has(relRef)) {
        const connectorId = relationshipRefToConnectorId.get(relRef);
        if (!placedConnectorIds.has(connectorId)) {
          placedConnectorIds.add(connectorId);
          viewMembers.push({ id: `vm-conn-${connEl.getAttribute('identifier') || relRef}`, view: viewId, objectType: 'connector', objectId: connectorId, order: 0, note: '', fromVmId, toVmId });
        }
      }
      // relationships that touched a junction are NOT placed from their original
      // <connection> element — the junction's own diagram node was skipped, so there's
      // no matching endpoint anyway. Bypass connectors for this view are placed below.
    }

    // ---------- nested-shape Composition/Aggregation detection ----------
    // Catches relationships the explicit-<connection> loop above missed entirely
    // because the diagram represents them via nesting instead of a line (see the
    // collectNestedElementPairs doc comment). If the underlying relationship was
    // already imported as a normal connector, just add the missing viewMember for this
    // view, reusing that connector, and note the viewMember since the connector itself
    // isn't new. If the relationship never became a connector at all (e.g. it touched a
    // junction and was absorbed into the bypass cross-product instead — a rare edge
    // case), create the connector directly and note IT instead, since in that case the
    // connector itself is what's newly created.
    const nestedPairs = [];
    collectNestedElementPairs(viewEl, [], nestedPairs);
    for (const { ancestorElRef, childElRef } of nestedPairs) {
      const relInfo = nestableRelByPairKey.get(`${ancestorElRef}|${childElRef}`);
      if (!relInfo) continue;
      let connectorId = relationshipRefToConnectorId.get(relInfo.id);
      let connectorWasFreshlyCreated = false;
      if (!connectorId) {
        connectorId = relInfo.id;
        connectorWasFreshlyCreated = true;
        connectors.push({
          id: connectorId, from: relInfo.from, to: relInfo.to, model: modelName, streams: [],
          note: 'Import detected nested shape without a connector; created.',
          connectorType: 'c', relationship: relInfo.type,
        });
        relationshipRefToConnectorId.set(relInfo.id, connectorId);
      }
      if (placedConnectorIds.has(connectorId)) continue; // already placed on this view via some other means
      const fromVmId = partIdToVmId.get(relInfo.from);
      const toVmId = partIdToVmId.get(relInfo.to);
      if (!fromVmId || !toVmId) continue; // one side wasn't actually placed as a real viewMember here — stay defensive even though nesting normally implies both are
      placedConnectorIds.add(connectorId);
      viewMembers.push({
        id: `vm-conn-nested-${connectorId}-${viewId}`, view: viewId, objectType: 'connector', objectId: connectorId,
        order: 0, note: connectorWasFreshlyCreated ? '' : 'Import detected nested shape without a connector; created.',
        fromVmId, toVmId,
      });
    }

    // place bypass connectors: wherever this view already shows both real endpoints,
    // wire them directly. Where only ONE side is already placed — the common case for a
    // relationship that visually terminated at a (now-removed) junction, whose OTHER
    // real endpoint (reached by flattening through it) was drawn only in some other
    // view — auto-place the missing side near its already-placed neighbor instead of
    // silently dropping the connector from this view. Newly auto-placed nodes are
    // registered into partIdToVmId too, so later bypass connectors in this same loop can
    // anchor off them (e.g. a junction with several downstream targets, none originally
    // placed here, still ends up with all of them visibly connected once the first one
    // is placed).
    let autoPlacedCount = 0;
    const placeNearAnchor = (partId, anchorVmId) => {
      const anchor = viewMembers.find((vm) => vm.id === anchorVmId);
      const part = partById.get(partId);
      const fillColor = (part && typeToFill.get(part.type)) || '#cccccc';
      autoPlacedCount += 1;
      const vmId = `vm-autoplaced-${partId}-${viewId}`;
      const vm = {
        id: vmId, view: viewId, objectType: 'part', objectId: partId,
        x: (anchor ? anchor.x : 60) + 200, y: (anchor ? anchor.y : 40) + (autoPlacedCount * 70),
        fillColor, order: 0, note: '', linkedViewName: '', isExternal: false, sectionId: '',
      };
      viewMembers.push(vm);
      partIdToVmId.set(partId, vmId);
      return vmId;
    };

    for (const c of connectors) {
      if (!c.id.startsWith('junction-bypass-')) continue;
      if (placedConnectorIds.has(c.id)) continue;
      let fromVmId = partIdToVmId.get(c.from);
      let toVmId = partIdToVmId.get(c.to);
      if (!fromVmId && !toVmId) continue; // neither endpoint has any anchor in this view — nothing sensible to place
      if (!fromVmId) fromVmId = placeNearAnchor(c.from, toVmId);
      if (!toVmId) toVmId = placeNearAnchor(c.to, fromVmId);
      if (!fromVmId || !toVmId) continue;
      placedConnectorIds.add(c.id);
      viewMembers.push({ id: `vm-conn-${c.id}-${viewId}`, view: viewId, objectType: 'connector', objectId: c.id, order: 0, note: '', fromVmId, toVmId });
    }
  }

  return { modelName, parts, connectors, views, viewMembers, unrecognizedTypes };
}

export { parseArchimateXml };
